name: Validar HTML

on:
  push:
  pull_request:

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Validar HTML1
        run: npx --yes html-validate Tarea6.html

      - name: Validar HTML2
        run: npx --yes html-validate Tarea7.html